# Generated by Django 5.1.5 on 2025-03-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.EmailField(max_length=254)),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Layout',
        ),
    ]
