# Generated by Django 5.1.5 on 2025-03-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_service_alter_category_description_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='address',
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
