# Generated by Django 5.1.5 on 2025-03-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_remove_service_address_service_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Image',
            field=models.ImageField(upload_to='cat_image/'),
        ),
    ]
