# Generated by Django 5.1.5 on 2025-03-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nm_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('service_type', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=50)),
                ('Map_Link', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='job_type',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
