# Generated by Django 5.1.5 on 2025-03-11 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nm_app', '0002_service_form_alter_job_type_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_form',
            name='Map_Link',
        ),
    ]
