# Generated by Django 5.1.5 on 2025-03-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nm_app', '0003_remove_service_form_map_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_form',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='service_form',
            name='service_type',
            field=models.CharField(max_length=50),
        ),
    ]
