# Generated by Django 5.1.5 on 2025-03-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nm_app', '0005_user_adhar_pan_user_certificate_user_expirience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
