# Generated by Django 5.1.5 on 2025-03-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nm_app', '0008_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, default='customer', max_length=255, null=True),
        ),
    ]
