# Generated by Django 5.1.5 on 2025-03-21 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nm_app', '0010_service_form_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_form',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service_form',
            name='payment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service_form',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ServiceResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.IntegerField()),
                ('status', models.CharField(blank=True, default='Pending', max_length=255, null=True)),
                ('maid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nm_app.service_form')),
            ],
        ),
    ]
