# Generated by Django 5.1.5 on 2025-03-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nm_app', '0011_service_form_is_paid_service_form_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceresponse',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
