# Generated by Django 5.1.5 on 2025-03-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nm_app', '0012_serviceresponse_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceresponse',
            name='is_send',
            field=models.BooleanField(default=True),
        ),
    ]
