# Generated by Django 5.1.5 on 2025-03-21 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nm_app', '0013_serviceresponse_is_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceresponse',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_response', to='nm_app.service_form'),
        ),
    ]
