# Generated by Django 5.1.5 on 2025-03-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nm_app', '0014_alter_serviceresponse_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_form',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
