# Generated by Django 5.2 on 2025-04-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nm_app', '0019_alter_user_speciality_nannyreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
