# Generated by Django 5.2 on 2025-04-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nm_app', '0020_subscription_end_date_subscription_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceresponse',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
    ]
